### ISSUE TITLE
Upgrade PyFxA and add tests to confirm that fxa-generation fields are correctly handled.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/tokenserver#182]
Once [this issue](https://github.com/mozilla-services/tokenserver/issues/182) is done, we can jump into the changes we need to make here in the tokenserver.

To support the larger efforts to [get the FxA Rust Component into Desktop](https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Integrate+FxA+rust+component+into+desktop), we first need to get Sync completely migrated [away from BrowserID over to OAuth](https://docs.google.com/document/d/1Qifi2p2YqqqY_A1oKeKHpxWIqhbZsEnNkW_YNaOoJ5k/edit#heading=h.x1rt6ia1h60i).

**Comment by rfk** [comment]
Re: "confirm that generation fields are correctly handled", we need to add a bit of logic so that *if* the OAuth verifier returns a `generation` field, then it gets reflected as `fxa-generation` in the `idpClaims` dict here:

* https://github.com/mozilla-services/tokenserver/blob/f038656242dd7c53565d69486a1f2640fadb3cfc/tokenserver/verifiers.py#L238

And add a corresponding test in this file:

* https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/tests/test_oauth_verifier.py

The value of `fxa-generation` should be an int, not a string.

For completeness we could also consider updating the mock verifier in the service tests to sometimes return a generation number, but I don't know up much churn that would induce:

* https://github.com/mozilla-services/tokenserver/blob/f038656242dd7c53565d69486a1f2640fadb3cfc/tokenserver/tests/test_service.py#L114
