### ISSUE TITLE
Browser id removal - confirm what caused the CPU spike.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/tokenserver#198]
In https://github.com/mozilla-services/tokenserver/issues/182, we upgraded PyFxa to support the browserId removal work. Unfortunately, we had to roll that change back out as we found perf issues in the [attempt to deploy](https://bugzilla.mozilla.org/show_bug.cgi?id=1644955).

Let's see if we can pinpoint the issue (likely within PyFxa) that's causing the regression before we  move forward. We may be able to mitigate this by bumping up tokenserver instances but it's worth understanding what caused the issue before rolling the PyFxA work to prod.

**Comment by rfk** [comment]
> we found perf issues in the attempt to deploy.

I suspect the perf issue here was caused (at least in part) by a lack of caching, which meant we were fetching the keys from the FxA server on each verification attempt. That would explain the decrease in throughput (although not the spike in CPU).

I think an increase in CPU is somewhat expected here, since we're now doing local crypto operations to verify a token instead of posting it to a remote service.

**Comment by fzzzy** [comment]
At this point we are pretty sure the cpu spike was from lack of caching.

The increase in CPU that was expected from added crypto seems to have low enough overhead.
